import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TagekService {

  constructor() { }


  tagek: string[] = [
    "Pizzák",
    "Burgerek",
    "Tésztaételek",
    "Saláták",
    "Levesek",
    "Húsételek",
    "Halételek",
    "Vegetáriánus ételek",
    "Vegán ételek",
    "Gluténmentes ételek",
    "Laktózmentes ételek",
    "Sushi",
    "Indiai ételek",
    "Kínai ételek",
    "Thai ételek",
    "Mexikói ételek",
    "Mediterrán ételek",
    "Grillételek",
    "Street food",
    "Gyros",
    "Szendvicsek",
    "Reggelik",
    "Deszertek",
    "Fagylalt",
    "Csokoládé",
    "Torták",
    "Palacsinták",
    "Péksütemények",
    "Kávé",
    "Teák",
    "Ásványvizek",
    "Üdítők",
    "Gyümölcslevek",
    "Smoothie-k",
    "Koktélok",
    "Sörök",
    "Borok",
    "Whisky-k",
    "Gin",
    "Rum",
    "Vodka",
    "Likőrök",
    "Cider",
    "Szeszes italok",
    "Koktél alapanyagok",
    "Cappuccino",
    "Latte macchiato",
    "Espresso",
    "Filterkávé",
    "Tejeskávék",
    "Hideg kávék",
    "Alternatív kávék",
    "Cukormentes kávék",
    "Tejes italok",
    "Fine dining",
    "Báréttermek",
    "Büfék",
    "Self-service éttermek",
    "Gasztronómiai éttermek",
    "BBQ éttermek",
    "Éttermek különleges ételkülönlegességekkel",
    "Garnírozások",
    "Szószok",
    "Fűszerek",
    "Sók",
    "Olajok",
    "Ecetek",
    "Zöldfűszerek",
    "Csípős szószok",
    "Chutney-k",
    "Mártások",
    "Eljegyzések",
    "Születésnapok",
    "Esküvők",
    "Céges rendezvények",
  ]
}
